import { Sparkles, Shield, DollarSign, Video, Target, Wallet, Trophy, TrendingUp, Lock } from 'lucide-react'
import { stacksIntroStep } from '../introduction/stacks-intro'

export const hermeticaData = {
    id: 'hermetica',
    name: 'Hermetica',
    tagline: 'Bitcoin-Backed Yield-Bearing Stablecoin',
    icon: '🔷',
    color: 'blue',
    totalXP: 2000,
    steps: [
      stacksIntroStep,
      {
        id: 2,
        title: 'Welcome to Hermetica',
        type: 'learn',
        duration: '8 min',
        xp: 150,
        icon: Sparkles,
        color: 'purple',
        content: {
          description: 'Discover the first Bitcoin-backed synthetic dollar',
          videoUrl: 'https://drive.google.com/file/d/1dAWke97dRgLvfifhYzYI4j4q8Y-onbPJ/preview',
          images: [
            {
              url: 'https://2201013687-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2Fxp26OjT5H1o55M1QMDI4%2Fuploads%2F3ITYZcg8oNso1aUVaQFo%2FTop%20Funds%20and%20Founders.PNG?alt=media&token=cfc4e3b7-83ec-4e4e-aa16-06dfe3910050',
              caption: 'Hermetica Team - Crypto Veterans from Kraken and State Street'
            }
          ],
          textGuide: [
            '**Hermetica** is built by crypto veterans with previous experience at **Kraken and State Street**. They\'re Bitcoiners building products for Bitcoiners.',
            '**The Problem with Stablecoins**: Most stablecoins offer **0% APY**, meaning your USD-denominated holdings lose value daily due to inflation. Additionally, most stablecoins like **USDC and Tether** rely on the traditional banking system, creating dependencies on banks remaining operational, solvent, and crypto-friendly.',
            'The **Silicon Valley Bank crisis** exposed these risks when USDC traded **12% below peg**. There was no yield-bearing dollar backed by **Bitcoin (the hardest asset)** and native to the **Bitcoin blockchain (the most secure)**.',
            '**Hermetica\'s Solution**: **USDh** - The first **Bitcoin-backed, yield-bearing synthetic dollar** outside the fiat system. USDh earns you **up to 15% APY** from funding payments generated by short perpetual futures positions.',
            'USDh is **Bitcoin-backed**, pairing Bitcoin with a short perpetual futures position to create a price-stable dollar. All Bitcoin is held at institutional-grade custodians like **Copper** and **Ceffu**, and the protocol is audited by top firms like **Clarity Alliance** and **Strata Labs**.'
          ],
          stats: [
            { label: 'APY', value: 'Up to 15%', icon: '📈' },
            { label: 'Backing', value: '100% Bitcoin', icon: '₿' },
            { label: 'Custodians', value: 'Copper & Ceffu', icon: '🔒' },
            { label: 'Security', value: 'Audited', icon: '✅' }
          ],
          keyFacts: [
            'Earn up to 15% APY on your dollar holdings',
            '100% Bitcoin-backed - no banks, no fiat',
            'Institutional-grade custody (Copper, Ceffu)',
            'Audited by Clarity Alliance and Strata Labs',
            'Available on Bitcoin L1 (Runes) and L2 (Stacks)'
          ],
          sections: [
            {
              title: '🎯 The Innovation',
              text: 'USDh solves the stablecoin trilemma: yield-bearing, Bitcoin-backed, and native to Bitcoin. No reliance on traditional banks or fiat systems.'
            },
            {
              title: '🔷 Who We Are',
              text: 'Hermetica is built by crypto veterans from Kraken and State Street - Bitcoiners building for Bitcoiners.'
            }
          ],
          quiz: {
            question: 'What makes USDh different from traditional stablecoins like USDC?',
            options: [
              'USDh is backed by gold instead of dollars',
              'USDh is Bitcoin-backed, yields up to 15% APY, and doesn\'t rely on banks',
              'USDh can only be used on Ethereum',
              'USDh has a fixed supply like Bitcoin'
            ],
            correct: 1
          }
        }
      },
      {
        id: 3,
        title: 'How USDh Works: Mint Mechanism',
        type: 'learn',
        duration: '10 min',
        xp: 200,
        icon: DollarSign,
        color: 'cyan',
        content: {
          description: 'Learn how USDh is created and backed by Bitcoin',
          textGuide: [
            '**Minting USDh** is the process of creating new stablecoins, while **redeeming USDh** is exchanging these stablecoins for Bitcoin. USDh is issued on **Bitcoin Layer 1 through Runes** and **Bitcoin Layer 2 through Stacks**.',
            'Any registered business or individual in an approved jurisdiction who has completed Hermetica\'s **KYC and AML processes** can mint USDh by depositing Bitcoin. These **Approved Participants (APs)** can also redeem USDh directly through Hermetica.',
            '**For everyone else**: You can **purchase USDh through open DeFi markets without completing KYC/KYB**. Available on exchanges like **Magic Eden, DotSwap, Velar, and Bitflow**.',
            '**Infrastructure**: All Bitcoin in the protocol is held at institutional-grade custodians **Copper** and **Ceffu**. Their **Off-Exchange Settlement (OES)** solutions allow Hermetica to mirror funds onto centralized exchanges for trading, while holding assets in a **bankruptcy-remote Trust** off the exchange\'s balance sheet.',
            'Hermetica trades on the **4 biggest centralized futures exchanges** representing over **$20B in BTCUSD perp open interest**: Binance, ByBit, Bitget, and OKX. The **short perpetual futures position delta-hedges the BTC** in the protocol and locks in the dollar value, represented on-chain as USDh.'
          ],
          images: [
            {
              url: 'https://2201013687-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2Fxp26OjT5H1o55M1QMDI4%2Fuploads%2F6QDqb1tA1zcNIAOdKDXG%2FOverall%20Process%20of%20USDh.PNG?alt=media&token=2599dddb-f861-49cf-aa02-587413b39989',
              caption: 'Overall Process of USDh'
            }
          ],
          keyInfrastructure: [
            { component: 'Custodians', name: 'Copper & Ceffu', role: 'Hold all Bitcoin assets', icon: '🏦' },
            { component: 'Exchanges', name: 'Binance, ByBit, Bitget, OKX', role: 'Trade perp futures', icon: '📊' },
            { component: 'Settlement', name: 'Off-Exchange Settlement (OES)', role: 'Bankruptcy-remote custody', icon: '🔐' },
            { component: 'On-Chain', name: 'Bitcoin L1 (Runes) & L2 (Stacks)', role: 'Issue USDh tokens', icon: '⚡' }
          ],
          sections: [
            {
              title: '🏦 Institutional-Grade Security',
              text: 'All Bitcoin held at Copper and Ceffu with Off-Exchange Settlement. Assets stay in bankruptcy-remote Trust, never on exchange balance sheets.'
            },
            {
              title: '💎 Delta-Neutral Strategy',
              text: 'Short perpetual futures position perfectly hedges BTC price movements, locking in dollar value while earning funding rate yield.'
            }
          ],
          quiz: {
            question: 'How does Hermetica maintain USDh\'s dollar peg?',
            options: [
              'By holding dollars in a bank account',
              'By using a short perpetual futures position to delta-hedge Bitcoin',
              'By burning tokens when price drops',
              'By using an algorithmic rebasing mechanism'
            ],
            correct: 1
          }
        }
      },
      {
        id: 4,
        title: 'Stability & Security Mechanisms',
        type: 'learn',
        duration: '10 min',
        xp: 200,
        icon: Shield,
        color: 'emerald',
        content: {
          description: 'Understand how USDh maintains its peg and security',
          textGuide: [
            '**Maintaining Stability**: The price of USDh is determined by market supply and demand. Depegging occurs when there\'s an imbalance between buyers and sellers.',
            '**Peg Maintenance via Arbitrage**: Since **Approved Participants (APs)** can mint and redeem USDh for **one USD** from the protocol, they\'re incentivized to arbitrage any imbalance. If USDh drops below $1, APs buy at a discount and redeem $1 worth of assets for profit. If USDh trades above $1, APs mint for $1 and sell into the market.',
            '**Risk Management System**: Hermetica\'s risk engine runs checks **every 100 milliseconds** and reconciles liabilities with assets and perpetual futures positions. Multiple risk engines run in parallel across **multiple geographic locations and cloud providers** to mitigate third-party failure.',
            '**Hermetica Reserve Fund**: A reserve of assets maintained by Hermetica to safeguard against **negative funding rate environments** and other unforeseen adverse events. The fund takes a portion of protocol yield during positive funding rates and sets it aside for periods of negative funding.',
            '**Off-Exchange Settlement Security**: Hermetica uses institutional-grade custodians with **Multi-Party Computation (MPC) wallets** to eliminate single points of failure. The collateral uses a **2-of-3 multi-signer schema**, where Hermetica Labs, the custodian, and a third party each hold a key. Hermetica\'s key is protected with a **4-of-8 multi-approver scheme**.',
            '**Audits**: Hermetica conducts regular comprehensive security audits with independent third-party services like **Clarity Alliance** and **Strata Labs**. Both custodians (Copper and Ceffu) have maintained a **perfect track record with no hacks or loss of customer funds** since inception.'
          ],
          riskControls: [
            { mechanism: 'AP Arbitrage', description: 'Mint/redeem at $1 to maintain peg', frequency: 'Continuous', icon: '⚖️' },
            { mechanism: 'Risk Engine', description: 'Reconciles assets vs liabilities', frequency: 'Every 100ms', icon: '🔍' },
            { mechanism: 'Reserve Fund', description: 'Protects against negative funding', frequency: 'Daily', icon: '🛡️' },
            { mechanism: 'MPC Wallets', description: '2-of-3 multi-sig, 4-of-8 approvers', frequency: 'Always', icon: '🔐' }
          ],
          securityLayers: [
            'Institutional custodians: Copper & Ceffu',
            'Off-Exchange Settlement (OES) - bankruptcy-remote',
            'Multi-Party Computation (MPC) wallets',
            '2-of-3 multi-signer + 4-of-8 multi-approver',
            'Audited by Clarity Alliance & Strata Labs',
            'Parallel risk engines across multiple geos'
          ],
          sections: [
            {
              title: '⚖️ Arbitrage Keeps the Peg',
              text: 'Approved Participants can mint/redeem at $1, creating instant arbitrage opportunities whenever USDh trades away from peg.'
            },
            {
              title: '🔐 Multi-Layer Security',
              text: 'MPC wallets, institutional custody, OES, and continuous risk monitoring protect all Bitcoin collateral.'
            }
          ],
          quiz: {
            question: 'How often does Hermetica\'s risk engine check and reconcile positions?',
            options: [
              'Once per day',
              'Once per hour',
              'Every 10 seconds',
              'Every 100 milliseconds'
            ],
            correct: 3
          }
        }
      },
      {
        id: 5,
        title: 'Yield Mechanism & Funding Rates',
        type: 'learn',
        duration: '10 min',
        xp: 200,
        icon: TrendingUp,
        color: 'yellow',
        content: {
          description: 'Learn how USDh generates up to 15% APY',
          videoUrl: 'https://drive.google.com/file/d/1v8uqfZa2a2qv_Fj5iEabU5mF9mjRW08-/preview',
          images: [
            {
              url: 'https://2201013687-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2Fxp26OjT5H1o55M1QMDI4%2Fuploads%2FtUa7mS70S9RJ82p8qH46%2FHistorical%20Performance%20-%20September%202025.PNG?alt=media&token=75651245-a264-47ad-83fd-1b9c3608f318',
              caption: 'sUSDh Historical Performance - Average 10.56% APY'
            }
          ],
          textGuide: [
            '**Where the Yield Comes From**: The yield for **sUSDh (staked USDh)** is generated through **funding rate payments** from short perpetual futures positions used to stabilize the dollar value of USDh.',
            '**What is the Funding Rate?**: In the futures market, the **funding rate** aligns the price of perpetual futures contracts with the underlying spot price. Perpetual futures have no expiration date, so the funding rate acts as a continuous adjustment tool.',
            'When futures price trades **above spot price**, the funding rate increases, making it costly to maintain long positions. This incentivizes traders to exit longs or enter shorts, bringing futures price back to spot.',
            '**How Funding Rates Generate Yield**: The yield for USDh comes from the structural **demand for long leverage in Bitcoin**. As long as there\'s strong demand for leveraged long positions, the futures market tends to trade above spot prices, resulting in **higher funding rates that pay Hermetica\'s short positions**.',
            'The funding rate calculations on centralized exchanges include a **positive base to account for cost of capital**. As a result, funding rates are **positive even in a steady state** with equal shorts and longs, further ensuring sustainability of USDh yield.',
            '**Yield Distribution**: USDh yield is distributed to **stakers (sUSDh holders) on a daily basis**. In the event funding rate payments are negative, funds from the **Hermetica Reserve Fund** are used, ensuring **USDh yield is always neutral or positive**.'
          ],
          yieldBreakdown: [
            { source: 'Short Perp Funding', contribution: 'Primary', description: 'Funding payments from BTC perpetual shorts', icon: '📈' },
            { source: 'Long Demand Premium', contribution: 'Core Driver', description: 'High beta assets drive long leverage demand', icon: '⚡' },
            { source: 'Base Funding Rate', contribution: 'Guaranteed', description: 'Positive base rate for cost of capital', icon: '💰' },
            { source: 'Reserve Fund Backup', contribution: 'Downside Protection', description: 'Covers negative funding periods', icon: '🛡️' }
          ],
          fundingDynamics: [
            'Long leverage demand drives futures above spot',
            'Funding rate rises to rebalance market',
            'Short positions (Hermetica) receive payments',
            'Yield distributed daily to sUSDh holders',
            'Reserve fund covers any negative periods'
          ],
          sections: [
            {
              title: '📊 Sustainable Yield Model',
              text: 'Yield comes from structural long leverage demand in Bitcoin markets. Even in balanced markets, positive base funding rate ensures yield sustainability.'
            },
            {
              title: '🛡️ Downside Protection',
              text: 'Hermetica Reserve Fund kicks in during negative funding periods, ensuring yield is always neutral or positive for stakers.'
            }
          ],
          quiz: {
            question: 'What happens if funding rates turn negative?',
            options: [
              'Stakers lose money',
              'The protocol shuts down',
              'The Hermetica Reserve Fund covers the negative funding',
              'USDh is automatically converted to Bitcoin'
            ],
            correct: 2
          }
        }
      },
      {
        id: 6,
        title: 'How to Buy USDh',
        type: 'learn',
        duration: '8 min',
        xp: 150,
        icon: Video,
        color: 'blue',
        content: {
          description: 'Learn where and how to purchase USDh',
          textGuide: [
            'Anyone can buy USDh on **open DeFi markets without KYC**. You can also buy USDh directly from the **Hermetica app** at **app.hermetica.fi**.',
            '**On Hermetica App**: Visit app.hermetica.fi → Click "Swap" tab → Connect your wallet → Confirm currency and amount → Click "Swap" and confirm transaction.',
            '**On Magic Eden**: Visit the USDh page on Magic Eden → Connect your Bitcoin wallet → Choose the amount of USDh from listed lots → Confirm the transaction.',
            '**On DotSwap**: Visit the USDh swap page on DotSwap → Connect your Bitcoin wallet → Choose the amount of USDh → Confirm the transaction.',
            '**On Velar**: Visit the USDh swap page on Velar → Connect your Stacks wallet → Choose preferred currencies and amount → Confirm the transaction.',
            '**On Bitflow**: Visit the USDh swap page on Bitflow → Connect your Stacks wallet → Choose preferred currencies and amount → Confirm the transaction.'
          ],
          platforms: [
            { name: 'Hermetica App', url: 'app.hermetica.fi/swap', chain: 'Bitcoin & Stacks', kyc: 'No', icon: '🔷' },
            { name: 'Magic Eden', url: 'magiceden.io', chain: 'Bitcoin L1 (Runes)', kyc: 'No', icon: '🎨' },
            { name: 'DotSwap', url: 'dotswap.app', chain: 'Bitcoin L1 (Runes)', kyc: 'No', icon: '🔄' },
            { name: 'Velar', url: 'app.velar.com', chain: 'Stacks L2', kyc: 'No', icon: '⚡' },
            { name: 'Bitflow', url: 'app.bitflow.finance', chain: 'Stacks L2', kyc: 'No', icon: '💧' }
          ],
          buyingSteps: [
            { step: 1, action: 'Choose Platform', desc: 'Hermetica, Magic Eden, DotSwap, Velar, or Bitflow', icon: '🌐' },
            { step: 2, action: 'Connect Wallet', desc: 'Bitcoin wallet (L1) or Stacks wallet (L2)', icon: '🔗' },
            { step: 3, action: 'Select Amount', desc: 'Choose how much USDh to purchase', icon: '💵' },
            { step: 4, action: 'Confirm Trade', desc: 'Review and approve the transaction', icon: '✅' },
            { step: 5, action: 'Receive USDh', desc: 'USDh arrives in your wallet', icon: '🎉' }
          ],
          sections: [
            {
              title: '🌐 Multiple Options',
              text: 'Buy USDh on Hermetica app, Magic Eden, DotSwap (Bitcoin L1) or Velar, Bitflow (Stacks L2). No KYC required for open market purchases.'
            },
            {
              title: '⚡ Available on L1 & L2',
              text: 'USDh is issued on Bitcoin Layer 1 (Runes) and Layer 2 (Stacks), giving you flexibility in how you access it.'
            }
          ],
          quiz: {
            question: 'Do you need to complete KYC to buy USDh on open DeFi markets?',
            options: [
              'Yes, KYC is always required',
              'No, you can buy on open markets without KYC',
              'Only for amounts over $10,000',
              'Only on Bitcoin L1, not on Stacks L2'
            ],
            correct: 1
          }
        }
      },
      {
        id: 7,
        title: 'How to Stake USDh',
        type: 'learn',
        duration: '8 min',
        xp: 150,
        icon: Lock,
        color: 'pink',
        content: {
          description: 'Stake USDh to earn up to 15% APY',
          videoUrl: 'https://drive.google.com/file/d/10u0vYsUhg7kyQoIvhlyJUxvGgXB6zSSx/preview',
          textGuide: [
            '**Staking USDh** converts it to **sUSDh (staked USDh)**, which earns you **up to 15% APY** from funding rate payments. Yield is distributed **daily** to sUSDh holders.',
            '**To Stake on Hermetica App**: Go to app.hermetica.fi → Click "Stake" tab → Click profile icon → Confirm your preferred chain (Bitcoin L1 or Stacks L2) → Enter the amount of USDh → Click "Stake" → Confirm the transaction.',
            '**sUSDh vs USDh**: When you stake USDh, you receive **sUSDh** tokens representing your staked position. Your sUSDh balance **increases daily as yield accrues**. When you unstake, you receive your original USDh **plus all earned yield**.',
            '**Yield is Compounding**: The APY shown is the **annual percentage yield** if yield were reinvested. Since yield accrues to your sUSDh balance daily, you automatically benefit from **daily compounding**.',
            '**Unstaking**: You can unstake anytime by going to the Stake tab, clicking "Unstake", entering the amount, and confirming. You\'ll receive USDh equal to your sUSDh balance (original stake + all accrued yield).'
          ],
          stakingFlow: [
            { step: 1, action: 'Visit Hermetica App', desc: 'Go to app.hermetica.fi/stake', icon: '🌐' },
            { step: 2, action: 'Connect Wallet', desc: 'Bitcoin or Stacks wallet', icon: '🔗' },
            { step: 3, action: 'Select Chain', desc: 'Bitcoin L1 (Runes) or Stacks L2', icon: '⚡' },
            { step: 4, action: 'Enter Amount', desc: 'Choose how much USDh to stake', icon: '💵' },
            { step: 5, action: 'Confirm Stake', desc: 'Approve transaction and receive sUSDh', icon: '✅' },
            { step: 6, action: 'Earn Yield', desc: 'Up to 15% APY, distributed daily', icon: '📈' }
          ],
          yieldComparison: [
            { asset: 'Traditional Stablecoins', apy: '0%', backing: 'Fiat/Banks', risk: 'Bank dependency', icon: '💵' },
            { asset: 'USDh (Unstaked)', apy: '0%', backing: '100% Bitcoin', risk: 'Low', icon: '🔷' },
            { asset: 'sUSDh (Staked)', apy: 'Up to 15%', backing: '100% Bitcoin', risk: 'Low', icon: '💎' }
          ],
          sections: [
            {
              title: '💎 Automatic Compounding',
              text: 'Yield accrues daily to your sUSDh balance. No need to manually claim or reinvest - it\'s all automatic.'
            },
            {
              title: '🔓 Unstake Anytime',
              text: 'No lock-up periods. Unstake whenever you want and receive your original USDh plus all earned yield.'
            }
          ],
          quiz: {
            question: 'What token do you receive when you stake USDh?',
            options: [
              'More USDh',
              'Bitcoin (BTC)',
              'sUSDh (staked USDh)',
              'Hermetica governance tokens'
            ],
            correct: 2
          }
        }
      },
      {
        id: 8,
        title: 'Understanding Risks',
        type: 'learn',
        duration: '10 min',
        xp: 200,
        icon: Shield,
        color: 'red',
        content: {
          description: 'Learn about the risks associated with USDh',
          textGuide: [
            '**Collateral Risk**: USDh is backed by **Bitcoin held at institutional custodians** (Copper, Ceffu). While these custodians have perfect security records, custodial risk always exists. Hermetica uses **Off-Exchange Settlement and MPC wallets** to minimize this.',
            '**Exchange Risk**: Hermetica trades perpetual futures on **Binance, ByBit, Bitget, and OKX**. While diversified across 4 major exchanges, exchange outages or failures could impact operations. **Only unsettled PnL is at risk**, not the bulk of collateral which stays in custody.',
            '**Liquidity Risk**: In extreme market conditions, there may be **insufficient liquidity** to unwind large positions. Hermetica manages this by **diversifying across multiple exchanges** and maintaining positions well below market capacity ($20B+ in total open interest).',
            '**Funding Rate Risk**: If Bitcoin perpetual futures enter a **prolonged negative funding environment**, the protocol would need to pay funding rates instead of receiving them. The **Hermetica Reserve Fund** is specifically designed to cover these periods and ensure yield remains neutral or positive.',
            '**General Smart Contract Risk**: Like all DeFi protocols, USDh has **smart contract risk**. Hermetica mitigates this through **comprehensive audits by Clarity Alliance and Strata Labs**, regular security reviews, and following blockchain security best practices.'
          ],
          riskMatrix: [
            { risk: 'Custodial', severity: 'Low', mitigation: 'Copper & Ceffu (perfect records), MPC wallets, OES', icon: '🏦' },
            { risk: 'Exchange', severity: 'Low-Medium', mitigation: '4 exchanges, only PnL exposed, bulk in custody', icon: '📊' },
            { risk: 'Liquidity', severity: 'Low', mitigation: '$20B+ OI capacity, multi-exchange diversification', icon: '💧' },
            { risk: 'Funding Rate', severity: 'Low', mitigation: 'Reserve Fund, historically positive funding', icon: '📈' },
            { risk: 'Smart Contract', severity: 'Low', mitigation: 'Audited by Clarity Alliance & Strata Labs', icon: '🔐' }
          ],
          mitigationStrategies: [
            'Institutional-grade custodians with perfect track records',
            'Off-Exchange Settlement - bankruptcy-remote custody',
            'Multi-Party Computation (MPC) wallets',
            'Diversification across 4 major exchanges',
            'Hermetica Reserve Fund for negative funding',
            'Comprehensive third-party security audits',
            'Risk engine monitoring every 100 milliseconds'
          ],
          sections: [
            {
              title: '🛡️ Multi-Layer Risk Management',
              text: 'Hermetica employs institutional-grade custody, diversification, reserve funds, and continuous monitoring to minimize all identified risks.'
            },
            {
              title: '📊 Transparent Risk Disclosure',
              text: 'Hermetica provides full transparency on all risks. Understanding risks is crucial for making informed decisions about using USDh.'
            }
          ],
          quiz: {
            question: 'What protects USDh users during negative funding rate periods?',
            options: [
              'The protocol automatically shuts down',
              'Users absorb the losses',
              'The Hermetica Reserve Fund covers negative funding',
              'Funding rates cannot be negative'
            ],
            correct: 2
          }
        }
      },
      {
        id: 9,
        title: 'Practice with Hermetica',
        type: 'practice',
        duration: '20 min',
        xp: 300,
        icon: Wallet,
        color: 'orange',
        content: {
          description: 'Practice buying and staking USDh on mainnet',
          steps: [
            {
              action: 'Connect Wallet',
              instruction: 'Connect your Bitcoin wallet (Leather, Xverse) or Stacks wallet to Hermetica app.',
              verification: 'wallet'
            },
            {
              action: 'Visit Hermetica App',
              instruction: 'Navigate to app.hermetica.fi and explore the Swap and Stake interfaces.',
              verification: 'balance'
            },
            {
              action: 'Buy USDh',
              instruction: 'Purchase USDh on Hermetica Swap, or on Magic Eden, DotSwap, Velar, or Bitflow.',
              verification: 'transaction'
            },
            {
              action: 'Stake USDh',
              instruction: 'Stake your USDh to receive sUSDh and start earning up to 15% APY.',
              verification: 'position'
            },
            {
              action: 'Monitor Yield',
              instruction: 'Check your sUSDh balance growing daily as yield accrues automatically.',
              verification: 'balance'
            }
          ]
        }
      },
      {
        id: 10,
        title: 'Hermetica Mastery Quiz',
        type: 'quiz',
        duration: '15 min',
        xp: 300,
        icon: Trophy,
        color: 'purple',
        content: {
          description: 'Prove your mastery of Hermetica and earn your NFT badge',
          questions: [
            {
              question: 'What is the primary backing for USDh?',
              options: [
                'US Dollar reserves in banks',
                'Bitcoin held at institutional custodians',
                'Ethereum and other altcoins',
                'Gold and precious metals'
              ],
              correct: 1
            },
            {
              question: 'What APY can sUSDh stakers earn?',
              options: [
                'Up to 5%',
                'Fixed 10%',
                'Up to 15%',
                'No yield'
              ],
              correct: 2
            },
            {
              question: 'Which custodians hold Hermetica\'s Bitcoin collateral?',
              options: [
                'Coinbase and Gemini',
                'Copper and Ceffu',
                'Binance and Kraken',
                'BitGo and Fireblocks'
              ],
              correct: 1
            },
            {
              question: 'How does Hermetica maintain USDh\'s dollar peg?',
              options: [
                'Using an algorithmic rebasing mechanism',
                'By holding dollars in a bank account',
                'Through short perpetual futures positions that delta-hedge Bitcoin',
                'By burning tokens when price drops'
              ],
              correct: 2
            },
            {
              question: 'Where does USDh\'s yield come from?',
              options: [
                'Lending Bitcoin to institutions',
                'Funding rate payments from short perpetual futures positions',
                'Transaction fees from users',
                'Mining rewards'
              ],
              correct: 1
            },
            {
              question: 'How often does Hermetica\'s risk engine check positions?',
              options: [
                'Once per hour',
                'Every 10 seconds',
                'Every 100 milliseconds',
                'Once per day'
              ],
              correct: 2
            },
            {
              question: 'Do you need KYC to buy USDh on open DeFi markets?',
              options: [
                'Yes, always required',
                'No, you can buy without KYC',
                'Only for amounts over $10,000',
                'Only on Stacks L2'
              ],
              correct: 1
            },
            {
              question: 'What happens during negative funding rate periods?',
              options: [
                'Stakers lose their yield',
                'The protocol shuts down temporarily',
                'The Hermetica Reserve Fund covers negative funding',
                'USDh is converted to Bitcoin'
              ],
              correct: 2
            },
            {
              question: 'Which firms have audited Hermetica\'s smart contracts?',
              options: [
                'Certik and OpenZeppelin',
                'Clarity Alliance and Strata Labs',
                'Trail of Bits and ConsenSys',
                'Quantstamp and PeckShield'
              ],
              correct: 1
            },
            {
              question: 'On which blockchains is USDh available?',
              options: [
                'Ethereum and Polygon',
                'Solana and Avalanche',
                'Bitcoin L1 (Runes) and Stacks L2',
                'Base and Arbitrum'
              ],
              correct: 2
            }
          ]
        }
      }
    ]
}
